# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kli1\PycharmProjects\irs-parser\irsparser.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1134, 831)
        self.IRS = QtGui.QTabWidget(Dialog)
        self.IRS.setGeometry(QtCore.QRect(10, 20, 1091, 781))
        self.IRS.setObjectName(_fromUtf8("IRS"))
        self.tab_xp = QtGui.QWidget()
        self.tab_xp.setObjectName(_fromUtf8("tab_xp"))
        self.xptextEdit = QtGui.QTextEdit(self.tab_xp)
        self.xptextEdit.setGeometry(QtCore.QRect(10, 20, 531, 721))
        self.xptextEdit.setObjectName(_fromUtf8("xptextEdit"))
        self.groupBox = QtGui.QGroupBox(self.tab_xp)
        self.groupBox.setGeometry(QtCore.QRect(580, 10, 501, 281))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit_xpname = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpname.setGeometry(QtCore.QRect(70, 20, 411, 20))
        self.lineEdit_xpname.setText(_fromUtf8(""))
        self.lineEdit_xpname.setObjectName(_fromUtf8("lineEdit_xpname"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 23, 46, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 143, 46, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_xpcountry = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpcountry.setGeometry(QtCore.QRect(70, 140, 411, 20))
        self.lineEdit_xpcountry.setText(_fromUtf8(""))
        self.lineEdit_xpcountry.setObjectName(_fromUtf8("lineEdit_xpcountry"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 173, 46, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit_xpphone = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpphone.setGeometry(QtCore.QRect(70, 170, 411, 20))
        self.lineEdit_xpphone.setText(_fromUtf8(""))
        self.lineEdit_xpphone.setObjectName(_fromUtf8("lineEdit_xpphone"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 203, 51, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_xpavailability = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpavailability.setGeometry(QtCore.QRect(70, 200, 411, 20))
        self.lineEdit_xpavailability.setText(_fromUtf8(""))
        self.lineEdit_xpavailability.setObjectName(_fromUtf8("lineEdit_xpavailability"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 50, 46, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_xpcompany = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpcompany.setGeometry(QtCore.QRect(70, 50, 411, 20))
        self.lineEdit_xpcompany.setText(_fromUtf8(""))
        self.lineEdit_xpcompany.setObjectName(_fromUtf8("lineEdit_xpcompany"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 46, 20))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_xpaddress = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpaddress.setGeometry(QtCore.QRect(70, 80, 411, 20))
        self.lineEdit_xpaddress.setText(_fromUtf8(""))
        self.lineEdit_xpaddress.setObjectName(_fromUtf8("lineEdit_xpaddress"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 110, 46, 20))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_xpemail = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpemail.setGeometry(QtCore.QRect(70, 110, 411, 20))
        self.lineEdit_xpemail.setText(_fromUtf8(""))
        self.lineEdit_xpemail.setObjectName(_fromUtf8("lineEdit_xpemail"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 51, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_xpsdq = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpsdq.setGeometry(QtCore.QRect(70, 230, 411, 20))
        self.lineEdit_xpsdq.setText(_fromUtf8(""))
        self.lineEdit_xpsdq.setObjectName(_fromUtf8("lineEdit_xpsdq"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_xp)
        self.groupBox_2.setGeometry(QtCore.QRect(580, 420, 501, 291))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 63, 71, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_xpsn = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_xpsn.setGeometry(QtCore.QRect(80, 60, 411, 20))
        self.lineEdit_xpsn.setText(_fromUtf8(""))
        self.lineEdit_xpsn.setObjectName(_fromUtf8("lineEdit_xpsn"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 103, 46, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_xptype = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_xptype.setGeometry(QtCore.QRect(80, 100, 411, 20))
        self.lineEdit_xptype.setText(_fromUtf8(""))
        self.lineEdit_xptype.setObjectName(_fromUtf8("lineEdit_xptype"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 143, 46, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_xplocation = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_xplocation.setGeometry(QtCore.QRect(80, 140, 411, 20))
        self.lineEdit_xplocation.setText(_fromUtf8(""))
        self.lineEdit_xplocation.setObjectName(_fromUtf8("lineEdit_xplocation"))
        self.label_xpaction = QtGui.QLabel(self.groupBox_2)
        self.label_xpaction.setGeometry(QtCore.QRect(10, 260, 101, 20))
        self.label_xpaction.setObjectName(_fromUtf8("label_xpaction"))
        self.lineEdit_xpaction = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_xpaction.setGeometry(QtCore.QRect(120, 260, 371, 20))
        self.lineEdit_xpaction.setText(_fromUtf8(""))
        self.lineEdit_xpaction.setObjectName(_fromUtf8("lineEdit_xpaction"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 183, 46, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_xppart = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_xppart.setGeometry(QtCore.QRect(80, 180, 411, 20))
        self.lineEdit_xppart.setText(_fromUtf8(""))
        self.lineEdit_xppart.setObjectName(_fromUtf8("lineEdit_xppart"))
        self.lineEdit_xpcanister = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_xpcanister.setGeometry(QtCore.QRect(80, 220, 411, 20))
        self.lineEdit_xpcanister.setText(_fromUtf8(""))
        self.lineEdit_xpcanister.setObjectName(_fromUtf8("lineEdit_xpcanister"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 220, 61, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_26 = QtGui.QLabel(self.groupBox_2)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEdit_xptitle = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_xptitle.setGeometry(QtCore.QRect(80, 27, 411, 20))
        self.lineEdit_xptitle.setText(_fromUtf8(""))
        self.lineEdit_xptitle.setObjectName(_fromUtf8("lineEdit_xptitle"))
        self.xprstbtn = QtGui.QPushButton(self.tab_xp)
        self.xprstbtn.setGeometry(QtCore.QRect(590, 720, 75, 23))
        self.xprstbtn.setObjectName(_fromUtf8("xprstbtn"))
        self.xpsbmtbtn = QtGui.QPushButton(self.tab_xp)
        self.xpsbmtbtn.setGeometry(QtCore.QRect(990, 720, 75, 23))
        self.xpsbmtbtn.setObjectName(_fromUtf8("xpsbmtbtn"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_xp)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 300, 501, 101))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 33, 91, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lineEdit_xpentmntstat = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_xpentmntstat.setGeometry(QtCore.QRect(110, 30, 111, 20))
        self.lineEdit_xpentmntstat.setText(_fromUtf8(""))
        self.lineEdit_xpentmntstat.setObjectName(_fromUtf8("lineEdit_xpentmntstat"))
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        self.label_20.setGeometry(QtCore.QRect(270, 33, 41, 20))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_xpsla = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_xpsla.setGeometry(QtCore.QRect(310, 30, 111, 20))
        self.lineEdit_xpsla.setText(_fromUtf8(""))
        self.lineEdit_xpsla.setObjectName(_fromUtf8("lineEdit_xpsla"))
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setGeometry(QtCore.QRect(10, 73, 101, 20))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lineEdit_xpentmnttyp = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_xpentmnttyp.setGeometry(QtCore.QRect(110, 70, 111, 20))
        self.lineEdit_xpentmnttyp.setText(_fromUtf8(""))
        self.lineEdit_xpentmnttyp.setObjectName(_fromUtf8("lineEdit_xpentmnttyp"))
        self.IRS.addTab(self.tab_xp, _fromUtf8(""))
        self.tab_eva = QtGui.QWidget()
        self.tab_eva.setObjectName(_fromUtf8("tab_eva"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_eva)
        self.groupBox_5.setGeometry(QtCore.QRect(580, 440, 501, 271))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_42 = QtGui.QLabel(self.groupBox_5)
        self.label_42.setGeometry(QtCore.QRect(10, 33, 71, 20))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.lineEdit_evaSN = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaSN.setGeometry(QtCore.QRect(100, 30, 131, 20))
        self.lineEdit_evaSN.setObjectName(_fromUtf8("lineEdit_evaSN"))
        self.label_43 = QtGui.QLabel(self.groupBox_5)
        self.label_43.setGeometry(QtCore.QRect(250, 33, 46, 20))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.lineEdit_evaWWN = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaWWN.setGeometry(QtCore.QRect(300, 30, 181, 20))
        self.lineEdit_evaWWN.setObjectName(_fromUtf8("lineEdit_evaWWN"))
        self.label_44 = QtGui.QLabel(self.groupBox_5)
        self.label_44.setGeometry(QtCore.QRect(250, 63, 46, 20))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.lineEdit_evaLocation = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaLocation.setGeometry(QtCore.QRect(300, 60, 181, 20))
        self.lineEdit_evaLocation.setObjectName(_fromUtf8("lineEdit_evaLocation"))
        self.label_46 = QtGui.QLabel(self.groupBox_5)
        self.label_46.setGeometry(QtCore.QRect(10, 153, 71, 20))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.lineEdit_evaPartDescription = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaPartDescription.setGeometry(QtCore.QRect(100, 180, 391, 20))
        self.lineEdit_evaPartDescription.setObjectName(_fromUtf8("lineEdit_evaPartDescription"))
        self.label_54 = QtGui.QLabel(self.groupBox_5)
        self.label_54.setGeometry(QtCore.QRect(10, 93, 81, 20))
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.lineEdit_evaFailingHostName = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaFailingHostName.setGeometry(QtCore.QRect(100, 90, 131, 20))
        self.lineEdit_evaFailingHostName.setText(_fromUtf8(""))
        self.lineEdit_evaFailingHostName.setObjectName(_fromUtf8("lineEdit_evaFailingHostName"))
        self.label_55 = QtGui.QLabel(self.groupBox_5)
        self.label_55.setGeometry(QtCore.QRect(10, 123, 81, 20))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.lineEdit_evaType = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaType.setGeometry(QtCore.QRect(100, 120, 131, 20))
        self.lineEdit_evaType.setText(_fromUtf8(""))
        self.lineEdit_evaType.setObjectName(_fromUtf8("lineEdit_evaType"))
        self.label_56 = QtGui.QLabel(self.groupBox_5)
        self.label_56.setGeometry(QtCore.QRect(10, 63, 81, 20))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.lineEdit_evaProductNumner = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaProductNumner.setGeometry(QtCore.QRect(100, 60, 131, 20))
        self.lineEdit_evaProductNumner.setText(_fromUtf8(""))
        self.lineEdit_evaProductNumner.setObjectName(_fromUtf8("lineEdit_evaProductNumner"))
        self.lineEdit_evaPartNumber = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaPartNumber.setGeometry(QtCore.QRect(100, 150, 391, 20))
        self.lineEdit_evaPartNumber.setText(_fromUtf8(""))
        self.lineEdit_evaPartNumber.setObjectName(_fromUtf8("lineEdit_evaPartNumber"))
        self.label_57 = QtGui.QLabel(self.groupBox_5)
        self.label_57.setGeometry(QtCore.QRect(10, 180, 81, 20))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.lineEdit_evaRecommendedAction = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_evaRecommendedAction.setGeometry(QtCore.QRect(10, 230, 481, 20))
        self.lineEdit_evaRecommendedAction.setText(_fromUtf8(""))
        self.lineEdit_evaRecommendedAction.setObjectName(_fromUtf8("lineEdit_evaRecommendedAction"))
        self.label_59 = QtGui.QLabel(self.groupBox_5)
        self.label_59.setGeometry(QtCore.QRect(10, 210, 111, 20))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.textEdit_eva = QtGui.QTextEdit(self.tab_eva)
        self.textEdit_eva.setGeometry(QtCore.QRect(10, 20, 531, 721))
        self.textEdit_eva.setObjectName(_fromUtf8("textEdit_eva"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_eva)
        self.groupBox_6.setGeometry(QtCore.QRect(580, 10, 501, 281))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lineEdit_evaname = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_evaname.setGeometry(QtCore.QRect(70, 20, 411, 20))
        self.lineEdit_evaname.setObjectName(_fromUtf8("lineEdit_evaname"))
        self.label_47 = QtGui.QLabel(self.groupBox_6)
        self.label_47.setGeometry(QtCore.QRect(10, 23, 46, 20))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.groupBox_6)
        self.label_48.setGeometry(QtCore.QRect(10, 143, 46, 20))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.lineEdit_evacountry = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_evacountry.setGeometry(QtCore.QRect(70, 140, 411, 20))
        self.lineEdit_evacountry.setObjectName(_fromUtf8("lineEdit_evacountry"))
        self.label_49 = QtGui.QLabel(self.groupBox_6)
        self.label_49.setGeometry(QtCore.QRect(10, 173, 46, 20))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.label_50 = QtGui.QLabel(self.groupBox_6)
        self.label_50.setGeometry(QtCore.QRect(10, 203, 51, 20))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.lineEdit_evaavailablity = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_evaavailablity.setGeometry(QtCore.QRect(70, 200, 411, 20))
        self.lineEdit_evaavailablity.setObjectName(_fromUtf8("lineEdit_evaavailablity"))
        self.label_51 = QtGui.QLabel(self.groupBox_6)
        self.label_51.setGeometry(QtCore.QRect(10, 53, 46, 20))
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.lineEdit_evacompany = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_evacompany.setGeometry(QtCore.QRect(70, 50, 411, 20))
        self.lineEdit_evacompany.setObjectName(_fromUtf8("lineEdit_evacompany"))
        self.label_52 = QtGui.QLabel(self.groupBox_6)
        self.label_52.setGeometry(QtCore.QRect(10, 83, 46, 20))
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.lineEdit_evaaddress = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_evaaddress.setGeometry(QtCore.QRect(70, 80, 411, 20))
        self.lineEdit_evaaddress.setObjectName(_fromUtf8("lineEdit_evaaddress"))
        self.label_53 = QtGui.QLabel(self.groupBox_6)
        self.label_53.setGeometry(QtCore.QRect(10, 113, 46, 20))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.lineEdit_evaemail = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_evaemail.setGeometry(QtCore.QRect(70, 110, 411, 20))
        self.lineEdit_evaemail.setObjectName(_fromUtf8("lineEdit_evaemail"))
        self.lineEdit_evasdq = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_evasdq.setGeometry(QtCore.QRect(70, 230, 411, 20))
        self.lineEdit_evasdq.setObjectName(_fromUtf8("lineEdit_evasdq"))
        self.label_58 = QtGui.QLabel(self.groupBox_6)
        self.label_58.setGeometry(QtCore.QRect(10, 230, 51, 20))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.lineEdit_evaphone = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_evaphone.setGeometry(QtCore.QRect(70, 170, 411, 20))
        self.lineEdit_evaphone.setObjectName(_fromUtf8("lineEdit_evaphone"))
        self.eva_sbmtbtn = QtGui.QPushButton(self.tab_eva)
        self.eva_sbmtbtn.setGeometry(QtCore.QRect(990, 720, 75, 23))
        self.eva_sbmtbtn.setObjectName(_fromUtf8("eva_sbmtbtn"))
        self.eva_rstbtn = QtGui.QPushButton(self.tab_eva)
        self.eva_rstbtn.setGeometry(QtCore.QRect(590, 720, 75, 23))
        self.eva_rstbtn.setObjectName(_fromUtf8("eva_rstbtn"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_eva)
        self.groupBox_4.setGeometry(QtCore.QRect(580, 310, 501, 101))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(10, 33, 91, 20))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.lineEdit_evaEntitlementStatus = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_evaEntitlementStatus.setGeometry(QtCore.QRect(110, 30, 111, 20))
        self.lineEdit_evaEntitlementStatus.setText(_fromUtf8(""))
        self.lineEdit_evaEntitlementStatus.setObjectName(_fromUtf8("lineEdit_evaEntitlementStatus"))
        self.label_evaSLA = QtGui.QLabel(self.groupBox_4)
        self.label_evaSLA.setGeometry(QtCore.QRect(270, 33, 41, 20))
        self.label_evaSLA.setObjectName(_fromUtf8("label_evaSLA"))
        self.lineEdit_evaSLA = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_evaSLA.setGeometry(QtCore.QRect(310, 30, 111, 20))
        self.lineEdit_evaSLA.setText(_fromUtf8(""))
        self.lineEdit_evaSLA.setObjectName(_fromUtf8("lineEdit_evaSLA"))
        self.label_24 = QtGui.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(10, 73, 101, 20))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.lineEdit_evaEntitlementType = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_evaEntitlementType.setGeometry(QtCore.QRect(110, 70, 111, 20))
        self.lineEdit_evaEntitlementType.setText(_fromUtf8(""))
        self.lineEdit_evaEntitlementType.setObjectName(_fromUtf8("lineEdit_evaEntitlementType"))
        self.IRS.addTab(self.tab_eva, _fromUtf8(""))
        self.tab_pro = QtGui.QWidget()
        self.tab_pro.setObjectName(_fromUtf8("tab_pro"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_pro)
        self.groupBox_7.setGeometry(QtCore.QRect(580, 440, 501, 271))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_66 = QtGui.QLabel(self.groupBox_7)
        self.label_66.setGeometry(QtCore.QRect(10, 33, 71, 20))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.lineEdit_proSerialNumber = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_proSerialNumber.setGeometry(QtCore.QRect(120, 30, 113, 20))
        self.lineEdit_proSerialNumber.setObjectName(_fromUtf8("lineEdit_proSerialNumber"))
        self.label_67 = QtGui.QLabel(self.groupBox_7)
        self.label_67.setGeometry(QtCore.QRect(10, 73, 81, 20))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.lineEdit_proServerModel = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_proServerModel.setGeometry(QtCore.QRect(120, 70, 113, 20))
        self.lineEdit_proServerModel.setObjectName(_fromUtf8("lineEdit_proServerModel"))
        self.label_68 = QtGui.QLabel(self.groupBox_7)
        self.label_68.setGeometry(QtCore.QRect(10, 113, 46, 20))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.lineEdit_proLocation = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_proLocation.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.lineEdit_proLocation.setObjectName(_fromUtf8("lineEdit_proLocation"))
        self.label_69 = QtGui.QLabel(self.groupBox_7)
        self.label_69.setGeometry(QtCore.QRect(10, 193, 101, 20))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.lineEdit_proOSVersion = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_proOSVersion.setGeometry(QtCore.QRect(120, 190, 361, 20))
        self.lineEdit_proOSVersion.setObjectName(_fromUtf8("lineEdit_proOSVersion"))
        self.label_70 = QtGui.QLabel(self.groupBox_7)
        self.label_70.setGeometry(QtCore.QRect(10, 153, 46, 20))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.lineEdit_proPart = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_proPart.setGeometry(QtCore.QRect(120, 150, 361, 20))
        self.lineEdit_proPart.setObjectName(_fromUtf8("lineEdit_proPart"))
        self.label_90 = QtGui.QLabel(self.groupBox_7)
        self.label_90.setGeometry(QtCore.QRect(250, 33, 91, 20))
        self.label_90.setObjectName(_fromUtf8("label_90"))
        self.lineEdit_proProductNumber = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_proProductNumber.setGeometry(QtCore.QRect(360, 30, 113, 20))
        self.lineEdit_proProductNumber.setObjectName(_fromUtf8("lineEdit_proProductNumber"))
        self.label_91 = QtGui.QLabel(self.groupBox_7)
        self.label_91.setGeometry(QtCore.QRect(250, 70, 81, 21))
        self.label_91.setObjectName(_fromUtf8("label_91"))
        self.lineEdit_proServerName = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_proServerName.setGeometry(QtCore.QRect(360, 70, 113, 20))
        self.lineEdit_proServerName.setObjectName(_fromUtf8("lineEdit_proServerName"))
        self.label_92 = QtGui.QLabel(self.groupBox_7)
        self.label_92.setGeometry(QtCore.QRect(250, 113, 71, 20))
        self.label_92.setObjectName(_fromUtf8("label_92"))
        self.lineEdit_proSDQueue = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_proSDQueue.setGeometry(QtCore.QRect(360, 110, 113, 20))
        self.lineEdit_proSDQueue.setObjectName(_fromUtf8("lineEdit_proSDQueue"))
        self.label_93 = QtGui.QLabel(self.groupBox_7)
        self.label_93.setGeometry(QtCore.QRect(10, 230, 101, 20))
        self.label_93.setObjectName(_fromUtf8("label_93"))
        self.lineEdit_porRecommendedAction = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_porRecommendedAction.setGeometry(QtCore.QRect(120, 230, 361, 20))
        self.lineEdit_porRecommendedAction.setObjectName(_fromUtf8("lineEdit_porRecommendedAction"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab_pro)
        self.groupBox_8.setGeometry(QtCore.QRect(580, 10, 501, 281))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.lineEdit_proName = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_proName.setGeometry(QtCore.QRect(70, 20, 421, 20))
        self.lineEdit_proName.setText(_fromUtf8(""))
        self.lineEdit_proName.setObjectName(_fromUtf8("lineEdit_proName"))
        self.label_71 = QtGui.QLabel(self.groupBox_8)
        self.label_71.setGeometry(QtCore.QRect(10, 23, 46, 20))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.label_72 = QtGui.QLabel(self.groupBox_8)
        self.label_72.setGeometry(QtCore.QRect(10, 143, 46, 20))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.lineEdit_proCountry = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_proCountry.setGeometry(QtCore.QRect(70, 140, 421, 20))
        self.lineEdit_proCountry.setObjectName(_fromUtf8("lineEdit_proCountry"))
        self.label_73 = QtGui.QLabel(self.groupBox_8)
        self.label_73.setGeometry(QtCore.QRect(10, 173, 46, 20))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.lineEdit_proPhone = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_proPhone.setGeometry(QtCore.QRect(70, 170, 421, 20))
        self.lineEdit_proPhone.setObjectName(_fromUtf8("lineEdit_proPhone"))
        self.label_74 = QtGui.QLabel(self.groupBox_8)
        self.label_74.setGeometry(QtCore.QRect(10, 203, 61, 20))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.lineEdit_proAvailablity = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_proAvailablity.setGeometry(QtCore.QRect(70, 200, 421, 20))
        self.lineEdit_proAvailablity.setObjectName(_fromUtf8("lineEdit_proAvailablity"))
        self.label_75 = QtGui.QLabel(self.groupBox_8)
        self.label_75.setGeometry(QtCore.QRect(10, 53, 46, 20))
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.lineEdit_proCompany = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_proCompany.setGeometry(QtCore.QRect(70, 50, 421, 20))
        self.lineEdit_proCompany.setObjectName(_fromUtf8("lineEdit_proCompany"))
        self.label_76 = QtGui.QLabel(self.groupBox_8)
        self.label_76.setGeometry(QtCore.QRect(10, 83, 46, 20))
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.lineEdit_proAddress = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_proAddress.setGeometry(QtCore.QRect(70, 80, 421, 20))
        self.lineEdit_proAddress.setObjectName(_fromUtf8("lineEdit_proAddress"))
        self.label_77 = QtGui.QLabel(self.groupBox_8)
        self.label_77.setGeometry(QtCore.QRect(10, 113, 46, 20))
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.lineEdit_proEmail = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit_proEmail.setGeometry(QtCore.QRect(70, 110, 421, 20))
        self.lineEdit_proEmail.setObjectName(_fromUtf8("lineEdit_proEmail"))
        self.textEdit_5 = QtGui.QTextEdit(self.tab_pro)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 20, 531, 721))
        self.textEdit_5.setObjectName(_fromUtf8("textEdit_5"))
        self.pro_sbmtbtn = QtGui.QPushButton(self.tab_pro)
        self.pro_sbmtbtn.setGeometry(QtCore.QRect(1000, 720, 75, 23))
        self.pro_sbmtbtn.setObjectName(_fromUtf8("pro_sbmtbtn"))
        self.pro_rstbtn = QtGui.QPushButton(self.tab_pro)
        self.pro_rstbtn.setGeometry(QtCore.QRect(580, 720, 75, 23))
        self.pro_rstbtn.setObjectName(_fromUtf8("pro_rstbtn"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_pro)
        self.groupBox_11.setGeometry(QtCore.QRect(580, 310, 501, 101))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_25 = QtGui.QLabel(self.groupBox_11)
        self.label_25.setGeometry(QtCore.QRect(10, 33, 91, 20))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEdit_proEntitlementStatus = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_proEntitlementStatus.setGeometry(QtCore.QRect(110, 30, 111, 20))
        self.lineEdit_proEntitlementStatus.setText(_fromUtf8(""))
        self.lineEdit_proEntitlementStatus.setObjectName(_fromUtf8("lineEdit_proEntitlementStatus"))
        self.label_27 = QtGui.QLabel(self.groupBox_11)
        self.label_27.setGeometry(QtCore.QRect(270, 33, 41, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.lineEdit_proSLA = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_proSLA.setGeometry(QtCore.QRect(310, 30, 111, 20))
        self.lineEdit_proSLA.setText(_fromUtf8(""))
        self.lineEdit_proSLA.setObjectName(_fromUtf8("lineEdit_proSLA"))
        self.label_28 = QtGui.QLabel(self.groupBox_11)
        self.label_28.setGeometry(QtCore.QRect(10, 73, 101, 20))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lineEdit_proEntitlementType = QtGui.QLineEdit(self.groupBox_11)
        self.lineEdit_proEntitlementType.setGeometry(QtCore.QRect(110, 70, 111, 20))
        self.lineEdit_proEntitlementType.setText(_fromUtf8(""))
        self.lineEdit_proEntitlementType.setObjectName(_fromUtf8("lineEdit_proEntitlementType"))
        self.IRS.addTab(self.tab_pro, _fromUtf8(""))
        self.tab_ux = QtGui.QWidget()
        self.tab_ux.setObjectName(_fromUtf8("tab_ux"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_ux)
        self.groupBox_9.setGeometry(QtCore.QRect(580, 440, 501, 271))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_78 = QtGui.QLabel(self.groupBox_9)
        self.label_78.setGeometry(QtCore.QRect(10, 33, 71, 20))
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.lineEdit_78 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_78.setGeometry(QtCore.QRect(120, 30, 113, 20))
        self.lineEdit_78.setObjectName(_fromUtf8("lineEdit_78"))
        self.label_79 = QtGui.QLabel(self.groupBox_9)
        self.label_79.setGeometry(QtCore.QRect(10, 73, 46, 20))
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.lineEdit_79 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_79.setGeometry(QtCore.QRect(120, 70, 113, 20))
        self.lineEdit_79.setObjectName(_fromUtf8("lineEdit_79"))
        self.label_80 = QtGui.QLabel(self.groupBox_9)
        self.label_80.setGeometry(QtCore.QRect(10, 113, 46, 20))
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.lineEdit_80 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_80.setGeometry(QtCore.QRect(120, 110, 113, 20))
        self.lineEdit_80.setObjectName(_fromUtf8("lineEdit_80"))
        self.label_81 = QtGui.QLabel(self.groupBox_9)
        self.label_81.setGeometry(QtCore.QRect(10, 193, 101, 20))
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.lineEdit_81 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_81.setGeometry(QtCore.QRect(120, 190, 361, 20))
        self.lineEdit_81.setObjectName(_fromUtf8("lineEdit_81"))
        self.label_82 = QtGui.QLabel(self.groupBox_9)
        self.label_82.setGeometry(QtCore.QRect(10, 153, 46, 20))
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.lineEdit_82 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_82.setGeometry(QtCore.QRect(120, 150, 113, 20))
        self.lineEdit_82.setObjectName(_fromUtf8("lineEdit_82"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_ux)
        self.groupBox_10.setGeometry(QtCore.QRect(580, 10, 501, 261))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.lineEdit_83 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_83.setGeometry(QtCore.QRect(70, 20, 421, 20))
        self.lineEdit_83.setObjectName(_fromUtf8("lineEdit_83"))
        self.label_83 = QtGui.QLabel(self.groupBox_10)
        self.label_83.setGeometry(QtCore.QRect(10, 23, 46, 20))
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.label_84 = QtGui.QLabel(self.groupBox_10)
        self.label_84.setGeometry(QtCore.QRect(10, 143, 46, 20))
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.lineEdit_84 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_84.setGeometry(QtCore.QRect(70, 140, 421, 20))
        self.lineEdit_84.setObjectName(_fromUtf8("lineEdit_84"))
        self.label_85 = QtGui.QLabel(self.groupBox_10)
        self.label_85.setGeometry(QtCore.QRect(10, 173, 46, 20))
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.lineEdit_85 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_85.setGeometry(QtCore.QRect(70, 170, 421, 20))
        self.lineEdit_85.setObjectName(_fromUtf8("lineEdit_85"))
        self.label_86 = QtGui.QLabel(self.groupBox_10)
        self.label_86.setGeometry(QtCore.QRect(10, 203, 51, 20))
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.lineEdit_86 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_86.setGeometry(QtCore.QRect(70, 200, 421, 20))
        self.lineEdit_86.setObjectName(_fromUtf8("lineEdit_86"))
        self.label_87 = QtGui.QLabel(self.groupBox_10)
        self.label_87.setGeometry(QtCore.QRect(10, 53, 46, 20))
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.lineEdit_87 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_87.setGeometry(QtCore.QRect(70, 50, 421, 20))
        self.lineEdit_87.setObjectName(_fromUtf8("lineEdit_87"))
        self.label_88 = QtGui.QLabel(self.groupBox_10)
        self.label_88.setGeometry(QtCore.QRect(10, 83, 46, 20))
        self.label_88.setObjectName(_fromUtf8("label_88"))
        self.lineEdit_88 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_88.setGeometry(QtCore.QRect(70, 80, 421, 20))
        self.lineEdit_88.setObjectName(_fromUtf8("lineEdit_88"))
        self.label_89 = QtGui.QLabel(self.groupBox_10)
        self.label_89.setGeometry(QtCore.QRect(10, 113, 46, 20))
        self.label_89.setObjectName(_fromUtf8("label_89"))
        self.lineEdit_89 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_89.setGeometry(QtCore.QRect(70, 110, 421, 20))
        self.lineEdit_89.setObjectName(_fromUtf8("lineEdit_89"))
        self.textEdit_6 = QtGui.QTextEdit(self.tab_ux)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 20, 521, 721))
        self.textEdit_6.setObjectName(_fromUtf8("textEdit_6"))
        self.ux_sbmtbtn = QtGui.QPushButton(self.tab_ux)
        self.ux_sbmtbtn.setGeometry(QtCore.QRect(1000, 720, 75, 23))
        self.ux_sbmtbtn.setObjectName(_fromUtf8("ux_sbmtbtn"))
        self.ux_rstbtn = QtGui.QPushButton(self.tab_ux)
        self.ux_rstbtn.setGeometry(QtCore.QRect(590, 720, 75, 23))
        self.ux_rstbtn.setObjectName(_fromUtf8("ux_rstbtn"))
        self.groupBox_12 = QtGui.QGroupBox(self.tab_ux)
        self.groupBox_12.setGeometry(QtCore.QRect(580, 290, 501, 101))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.label_29 = QtGui.QLabel(self.groupBox_12)
        self.label_29.setGeometry(QtCore.QRect(10, 33, 91, 20))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.lineEdit_xpsn_11 = QtGui.QLineEdit(self.groupBox_12)
        self.lineEdit_xpsn_11.setGeometry(QtCore.QRect(110, 30, 111, 20))
        self.lineEdit_xpsn_11.setText(_fromUtf8(""))
        self.lineEdit_xpsn_11.setObjectName(_fromUtf8("lineEdit_xpsn_11"))
        self.label_30 = QtGui.QLabel(self.groupBox_12)
        self.label_30.setGeometry(QtCore.QRect(270, 33, 41, 20))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.lineEdit_xpsn_12 = QtGui.QLineEdit(self.groupBox_12)
        self.lineEdit_xpsn_12.setGeometry(QtCore.QRect(310, 30, 111, 20))
        self.lineEdit_xpsn_12.setText(_fromUtf8(""))
        self.lineEdit_xpsn_12.setObjectName(_fromUtf8("lineEdit_xpsn_12"))
        self.label_31 = QtGui.QLabel(self.groupBox_12)
        self.label_31.setGeometry(QtCore.QRect(10, 73, 101, 20))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lineEdit_xpsn_13 = QtGui.QLineEdit(self.groupBox_12)
        self.lineEdit_xpsn_13.setGeometry(QtCore.QRect(110, 70, 111, 20))
        self.lineEdit_xpsn_13.setText(_fromUtf8(""))
        self.lineEdit_xpsn_13.setObjectName(_fromUtf8("lineEdit_xpsn_13"))
        self.IRS.addTab(self.tab_ux, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.IRS.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.xptextEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.groupBox.setTitle(_translate("Dialog", "Customer Supplied Site Info", None))
        self.label.setText(_translate("Dialog", "name", None))
        self.label_2.setText(_translate("Dialog", "Country", None))
        self.label_3.setText(_translate("Dialog", "Phone", None))
        self.label_4.setText(_translate("Dialog", "Availability", None))
        self.label_5.setText(_translate("Dialog", "Company", None))
        self.label_11.setText(_translate("Dialog", "Address", None))
        self.label_12.setText(_translate("Dialog", "Email", None))
        self.label_6.setText(_translate("Dialog", "SDQueue", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Details", None))
        self.label_14.setText(_translate("Dialog", "Serial number", None))
        self.label_15.setText(_translate("Dialog", "XP type", None))
        self.label_16.setText(_translate("Dialog", "Location", None))
        self.label_xpaction.setText(_translate("Dialog", "Recommended action", None))
        self.label_18.setText(_translate("Dialog", "Part", None))
        self.label_19.setText(_translate("Dialog", "Error parts", None))
        self.label_26.setText(_translate("Dialog", "Case Title", None))
        self.xprstbtn.setText(_translate("Dialog", "Reset", None))
        self.xpsbmtbtn.setText(_translate("Dialog", "Submit", None))
        self.groupBox_3.setTitle(_translate("Dialog", "RSDC Detected Entitlement Details", None))
        self.label_17.setText(_translate("Dialog", "EntitlementStatus", None))
        self.label_20.setText(_translate("Dialog", "SLA", None))
        self.label_21.setText(_translate("Dialog", "Entitlement Type", None))
        self.IRS.setTabText(self.IRS.indexOf(self.tab_xp), _translate("Dialog", "XP", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Details", None))
        self.label_42.setText(_translate("Dialog", "Serial number", None))
        self.label_43.setText(_translate("Dialog", "WWN", None))
        self.label_44.setText(_translate("Dialog", "Location", None))
        self.label_46.setText(_translate("Dialog", "Part Number", None))
        self.label_54.setText(_translate("Dialog", "FailingHostName", None))
        self.label_55.setText(_translate("Dialog", "EVA Type", None))
        self.label_56.setText(_translate("Dialog", "Product Number", None))
        self.label_57.setText(_translate("Dialog", "Part Description", None))
        self.label_59.setText(_translate("Dialog", "Recommended action", None))
        self.textEdit_eva.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Customer Supplied Site Info", None))
        self.label_47.setText(_translate("Dialog", "name", None))
        self.label_48.setText(_translate("Dialog", "Country", None))
        self.label_49.setText(_translate("Dialog", "Phone", None))
        self.label_50.setText(_translate("Dialog", "Availability", None))
        self.label_51.setText(_translate("Dialog", "Company", None))
        self.label_52.setText(_translate("Dialog", "Address", None))
        self.label_53.setText(_translate("Dialog", "Email", None))
        self.label_58.setText(_translate("Dialog", "SDQueue", None))
        self.eva_sbmtbtn.setText(_translate("Dialog", "Submit", None))
        self.eva_rstbtn.setText(_translate("Dialog", "Reset", None))
        self.groupBox_4.setTitle(_translate("Dialog", "RSDC Detected Entitlement Details", None))
        self.label_22.setText(_translate("Dialog", "EntitlementStatus", None))
        self.label_evaSLA.setText(_translate("Dialog", "SLA", None))
        self.label_24.setText(_translate("Dialog", "Entitlement Type", None))
        self.IRS.setTabText(self.IRS.indexOf(self.tab_eva), _translate("Dialog", "EVA", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Details", None))
        self.label_66.setText(_translate("Dialog", "Serial number", None))
        self.label_67.setText(_translate("Dialog", "Server Model", None))
        self.label_68.setText(_translate("Dialog", "Location", None))
        self.label_69.setText(_translate("Dialog", "OS Version", None))
        self.label_70.setText(_translate("Dialog", "Part", None))
        self.label_90.setText(_translate("Dialog", "Product Number", None))
        self.label_91.setText(_translate("Dialog", "Server Name", None))
        self.label_92.setText(_translate("Dialog", "SD Queue", None))
        self.label_93.setText(_translate("Dialog", "Recommended action", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Customer Supplied Site Info", None))
        self.label_71.setText(_translate("Dialog", "name", None))
        self.label_72.setText(_translate("Dialog", "Country", None))
        self.label_73.setText(_translate("Dialog", "Phone", None))
        self.label_74.setText(_translate("Dialog", "Availability", None))
        self.label_75.setText(_translate("Dialog", "Company", None))
        self.label_76.setText(_translate("Dialog", "Address", None))
        self.label_77.setText(_translate("Dialog", "Email", None))
        self.textEdit_5.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.pro_sbmtbtn.setText(_translate("Dialog", "Submit", None))
        self.pro_rstbtn.setText(_translate("Dialog", "Reset", None))
        self.groupBox_11.setTitle(_translate("Dialog", "RSDC Detected Entitlement Details", None))
        self.label_25.setText(_translate("Dialog", "EntitlementStatus", None))
        self.label_27.setText(_translate("Dialog", "SLA", None))
        self.label_28.setText(_translate("Dialog", "Entitlement Type", None))
        self.IRS.setTabText(self.IRS.indexOf(self.tab_pro), _translate("Dialog", "ProLiant", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Details", None))
        self.label_78.setText(_translate("Dialog", "Serial number", None))
        self.label_79.setText(_translate("Dialog", "XP type", None))
        self.label_80.setText(_translate("Dialog", "Location", None))
        self.label_81.setText(_translate("Dialog", "Recommended action", None))
        self.label_82.setText(_translate("Dialog", "Part", None))
        self.groupBox_10.setTitle(_translate("Dialog", "Customer Supplied Site Info", None))
        self.label_83.setText(_translate("Dialog", "name", None))
        self.label_84.setText(_translate("Dialog", "Country", None))
        self.label_85.setText(_translate("Dialog", "Phone", None))
        self.label_86.setText(_translate("Dialog", "Availability", None))
        self.label_87.setText(_translate("Dialog", "Company", None))
        self.label_88.setText(_translate("Dialog", "Address", None))
        self.label_89.setText(_translate("Dialog", "Email", None))
        self.textEdit_6.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.ux_sbmtbtn.setText(_translate("Dialog", "Submit", None))
        self.ux_rstbtn.setText(_translate("Dialog", "Reset", None))
        self.groupBox_12.setTitle(_translate("Dialog", "RSDC Detected Entitlement Details", None))
        self.label_29.setText(_translate("Dialog", "EntitlementStatus", None))
        self.label_30.setText(_translate("Dialog", "SLA", None))
        self.label_31.setText(_translate("Dialog", "Entitlement Type", None))
        self.IRS.setTabText(self.IRS.indexOf(self.tab_ux), _translate("Dialog", "HPUX", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

